# Generated by Django 5.0.6 on 2024-07-28 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='has_insurance_benefit',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_EU',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_dutch',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_eligible',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_insured',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_living_at_home',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_student',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_working',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
