# Generated by Django 5.0.6 on 2024-10-10 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_profile_phone_number_alter_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_lead',
            field=models.BooleanField(null=True),
        ),
    ]
