# Generated by Django 5.0.6 on 2024-10-16 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_remove_profile_is_lead'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='number_of_landingpage_visits',
        ),
    ]
